sensor:
  - platform: pulse_meter
    pin: 12
    unit_of_measurement: 'kW'
    name: 'Power Meter House'
    state_class: measurement
    device_class: power
    filters:
      - multiply: 0.015  # 60/4000=0.015

    total:
      unit_of_measurement: 'kWh'
      accuracy_decimals: 3
      state_class: total_increasing
      device_class: energy
      name: 'Energy Meter House'
      filters:
        - multiply: 0.00025  # 1/4000=0.00025
