sensor:
  # WiFi signal
  - platform: wifi_signal
    name: "Power Meter WiFi Signal"
    update_interval: 120s

  # Pulse meter
  - platform: pulse_counter
    pin: 12
    unit_of_measurement: 'kW'
    name: 'Power Meter House'
    state_class: measurement
    device_class: power
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / 4000.0) * 1000.0);

    total:
      unit_of_measurement: 'kWh'
      accuracy_decimals: 3
      state_class: total_increasing
      device_class: energy
      name: 'Energy Meter House'
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / 4000.0);
